--Part 1--

In [151]:
import numpy as np


# current space occupation of the falling rock
rock1 = np.zeros((1,7),dtype=int)
rock1[0][2:6]=1
# print(rock1)

rock2 = np.zeros((3,7),dtype=int)
rock2[[0,1,1,1,2],[3,2,3,4,3]]=1
print(rock2)
indexlist_r2=[[0,1,1,1,2],[3,2,3,4,3]]

print(indexlist_r2)
test=np.array(indexlist_r2)
test[0]+=1
test=list(test)
print(test)
mylist=np.random.randint(0,8, size=(5,7))
print(mylist)
print(mylist[tuple(test)])

#current space occupation of the falling rock2
# print(rock2[tuple(indexlist_r2)])

rock3 = np.zeros((3,7),dtype=int)
rock3[[0,1,2,2,2],[4,4,2,3,4]]=1
# print(rock3)

rock4=np.zeros((4,7),dtype=int)
rock4[:,2]=1
# print(rock4)

[[0 0 0 1 0 0 0]
 [0 0 1 1 1 0 0]
 [0 0 0 1 0 0 0]]
[[0, 1, 1, 1, 2], [3, 2, 3, 4, 3]]
[array([1, 2, 2, 2, 3]), array([3, 2, 3, 4, 3])]
[[1 7 5 4 2 6 2]
 [7 0 7 7 4 6 7]
 [1 0 1 5 7 5 0]
 [3 2 3 3 2 5 3]
 [5 0 0 7 6 3 4]]
[7 1 5 7 3]


In [90]:
import numpy as np
space_l = np.zeros((4,7), dtype=int)
# space_l+=1


#after resting
# space_l[-1][2:6]=1
# print(space_l)

# intial space occupation of the falling rock
indexlist_r1=[[0],[2,3,4,5]]
indexlist_r2=[[0,1,1,1,2],[3,2,3,4,3]]
indexlist_r3=[[0,1,2,2,2],[4,4,2,3,4]]
indexlist_r4=[[0,1,2,3],[2,2,2,2]]

#make class object of each rock
def rock_move(rocktype, space,i):
    #rocktype.indexlist
    #check movement
    arr=np.array(rocktype.indexlist)
    if i % 2 == 0:
        #move right or left
        # if "<" and [0<j<6 for j in arr[1]]:
        #     arr[1]-=1
        # elif ">" and [0<j<6 for j in arr[1]]:
        #     arr[1]+=1
    else:
        #move down
        arr[0]+=1
    indexlist_update=list(arr)
    i+1
    return indexlist_update, i



def initiate_fall(rocktype, space):
    hp = np.where(space==1)[0][0] #highest point of resting rock
    # print(hp)
    #preparing for a new fall
    a = hp+3-space_l.shape[0]
    # print("hp:",hp, "space_l rows:",space_l.shape[0], "a:",a)
    add = np.zeros((a,7),dtype=int)
    np.vstack([rocktype,add,space])


In [147]:
y = np.arange(35).reshape(5,7)
print(y) 
indexlist = [[0,1], [0,2], [3,3]]
print ('indexlist:', indexlist)
indexlisttranspose = np.array(indexlist).T.tolist()
print ('indexlist.T:', indexlisttranspose)
print ('y[indexlist.T]:', y[ tuple(indexlisttranspose) ])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
indexlist: [[0, 1], [0, 2], [3, 3]]
indexlist.T: [[0, 0, 3], [1, 2, 3]]
y[indexlist.T]: [ 1  2 24]


In [33]:
A = np.array([[0, 1, 2], [0, 2, 0]])
newrow = [1, 2, 3]
A = np.vstack([A, newrow])
print(A)


[[0 1 2]
 [0 2 0]
 [1 2 3]]


In [26]:
row_l=[0 for i in range(7)]
print(row_l)
space_l = [row_l for i in range(4)]
for line in space_l:
    print(line)


mymatrix=[[1,2,9],[4,9,6],[7,8,9]]
val = 9
[(index, row.index(val)) for index, row in enumerate(mymatrix) if val in row]


[0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0]


[(0, 2), (1, 1), (2, 2)]